Update snyk-container.yml

diff --git a/.github/workflows/snyk-container.yml b/.github/workflows/snyk-container.yml
--- a/.github/workflows/snyk-container.yml
+++ b/.github/workflows/snyk-container.yml
@@ -49,6 +49,12 @@ jobs:
       with:
         image: local/danteproxy
         args: --file=Container/DOCKERFILE
+    - name: Check for SARIF file
+      run: |
+        if [ ! -f snyk.sarif ]; then
+          echo "SARIF file not found!"
+          exit 1
+        fi
     - name: Upload result to GitHub Code Scanning
       uses: github/codeql-action/upload-sarif@v3
       with:
